import logging
from config import IS_POSTGRES

logger = logging.getLogger(__name__)

if IS_POSTGRES:
    logger.info("🐘 PostgreSQL rejimi faollashtirildi (asyncpg Connection Pool).")
    from db_postgres import (
        init_db,
        close_db,
        get_db,
        is_referral_enabled,
        set_referral_enabled,
        register_referral,
        process_referral_connection_reward,
        get_user_referral_stats,
        get_user_language,
        set_user_language,
        is_media_already_captured,
        mark_media_as_captured,
        ensure_free_trial,
        get_user_subscription_status,
        save_archive_log,
        get_undelivered_archive_logs,
        mark_archive_logs_delivered,
        count_undelivered_messages,
        get_unnotified_expired_users,
        mark_expired_notified,
        get_unnotified_cutoff_users,
        mark_cutoff_notified,
        is_subscription_active,
        add_subscription,
        get_subscription_info,
        save_connection,
        get_connection_owner_chat,
        save_message,
        update_message_file_path,
        get_message,
        update_message_text,
        cleanup_old_messages,
        get_stats,
        get_admin_detailed_stats,
        get_all_broadcast_users,
        get_user_full_profile,
        admin_add_subscription_days,
        admin_revoke_subscription,
        get_db_info,
        is_user_business_connected,
        get_user_deleted_messages_count,
    )
    DB_ENGINE = "postgres"
else:
    logger.info("🗄 SQLite rejimi faollashtirildi (aiosqlite WAL).")
    from db_sqlite import (
        init_db,
        close_db,
        get_db,
        is_referral_enabled,
        set_referral_enabled,
        register_referral,
        process_referral_connection_reward,
        get_user_referral_stats,
        get_user_language,
        set_user_language,
        is_media_already_captured,
        mark_media_as_captured,
        ensure_free_trial,
        get_user_subscription_status,
        save_archive_log,
        get_undelivered_archive_logs,
        mark_archive_logs_delivered,
        count_undelivered_messages,
        get_unnotified_expired_users,
        mark_expired_notified,
        get_unnotified_cutoff_users,
        mark_cutoff_notified,
        is_subscription_active,
        add_subscription,
        get_subscription_info,
        save_connection,
        get_connection_owner_chat,
        save_message,
        update_message_file_path,
        get_message,
        update_message_text,
        cleanup_old_messages,
        get_stats,
        get_admin_detailed_stats,
        get_all_broadcast_users,
        get_user_full_profile,
        admin_add_subscription_days,
        admin_revoke_subscription,
        get_db_info,
        is_user_business_connected,
        get_user_deleted_messages_count,
    )
    DB_ENGINE = "sqlite"

__all__ = [
    "init_db",
    "close_db",
    "get_db",
    "is_referral_enabled",
    "set_referral_enabled",
    "register_referral",
    "process_referral_connection_reward",
    "get_user_referral_stats",
    "get_user_language",
    "set_user_language",
    "is_media_already_captured",
    "mark_media_as_captured",
    "ensure_free_trial",
    "get_user_subscription_status",
    "save_archive_log",
    "get_undelivered_archive_logs",
    "mark_archive_logs_delivered",
    "count_undelivered_messages",
    "get_unnotified_expired_users",
    "mark_expired_notified",
    "get_unnotified_cutoff_users",
    "mark_cutoff_notified",
    "is_subscription_active",
    "add_subscription",
    "get_subscription_info",
    "save_connection",
    "get_connection_owner_chat",
    "save_message",
    "update_message_file_path",
    "get_message",
    "update_message_text",
    "cleanup_old_messages",
    "get_stats",
    "get_admin_detailed_stats",
    "get_all_broadcast_users",
    "get_user_full_profile",
    "admin_add_subscription_days",
    "admin_revoke_subscription",
    "get_db_info",
    "is_user_business_connected",
    "get_user_deleted_messages_count",
    "DB_ENGINE",
]
